version: '3.8'

services:
  discord-bot-standalone:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: discord_bot_standalone
    restart: always
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
    ports:
      - "3000:3000"
    volumes:
      - bot_db_data:/app/data

volumes:
  bot_db_data:
