global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'discord-admin-webhook'

receivers:
  - name: 'discord-admin-webhook'
    webhook_configs:
      - url: 'http://backend:4000/api/v1/webhooks/alerts'
        send_resolved: true
